
import Head from 'next/head';

const AppLayout = ({ children }) => {
    return (
        <>
            <Head>
                <title>devter</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                {children}
            </main>
        </>);
}

export default AppLayout;